
[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "probots"
version = "0.0.1"
description = "Python module for Project Robots"
authors = [
    {name = "Jason Miller", email = "jason@thoughtparameters.com"}
]
readme = "README.md"
requires-python = ">=3.8"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
dependencies = [
    "click>=8.0",
    "fastapi>=0.68.0",
    "uvicorn>=0.15.0",
    "cryptography>=3.4",
    "pydantic>=1.8",
    "pytz>=2024.2",
    "sqlalchemy>=1.4",
    "psycopg2>=2.9",
    "alembic>=1.7"
]

[project.scripts]
robotsec = "probots.security.cli:main"


[tool.setuptools]
packages = ["probots"]
package-dir = {"" = "src"}

[tool.setuptools.package-data]
orbit = ["py.typed"]

[options]
zip_safe = false
include_package_data = true

